apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-node
  labels:
    app: my-simple-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-simple-node
  template:
    metadata:
      labels:
        app: my-simple-node
    spec:
      containers:
      - name: simple-node
        image: mhayes30125/simple-node
        ports:
        - containerPort: 80
